// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.1
// source: protos/crawler.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCookieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetCookieRequest) Reset() {
	*x = GetCookieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_crawler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCookieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookieRequest) ProtoMessage() {}

func (x *GetCookieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookieRequest.ProtoReflect.Descriptor instead.
func (*GetCookieRequest) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *GetCookieRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetCookieRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetCookieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cookie string `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
}

func (x *GetCookieResponse) Reset() {
	*x = GetCookieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_crawler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCookieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCookieResponse) ProtoMessage() {}

func (x *GetCookieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_crawler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCookieResponse.ProtoReflect.Descriptor instead.
func (*GetCookieResponse) Descriptor() ([]byte, []int) {
	return file_protos_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *GetCookieResponse) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

var File_protos_crawler_proto protoreflect.FileDescriptor

var file_protos_crawler_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x73, 0x7a, 0x74, 0x75, 0x65, 0x61, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x32, 0x83, 0x01, 0x0a, 0x07, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x12, 0x78, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x73, 0x7a, 0x74, 0x75, 0x65, 0x61, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x73, 0x7a, 0x74, 0x75,
	0x65, 0x61, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_crawler_proto_rawDescOnce sync.Once
	file_protos_crawler_proto_rawDescData = file_protos_crawler_proto_rawDesc
)

func file_protos_crawler_proto_rawDescGZIP() []byte {
	file_protos_crawler_proto_rawDescOnce.Do(func() {
		file_protos_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_crawler_proto_rawDescData)
	})
	return file_protos_crawler_proto_rawDescData
}

var file_protos_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_crawler_proto_goTypes = []interface{}{
	(*GetCookieRequest)(nil),  // 0: com.github.sztuea.grpc.crawler.v1.GetCookieRequest
	(*GetCookieResponse)(nil), // 1: com.github.sztuea.grpc.crawler.v1.GetCookieResponse
}
var file_protos_crawler_proto_depIdxs = []int32{
	0, // 0: com.github.sztuea.grpc.crawler.v1.Crawler.GetCookie:input_type -> com.github.sztuea.grpc.crawler.v1.GetCookieRequest
	1, // 1: com.github.sztuea.grpc.crawler.v1.Crawler.GetCookie:output_type -> com.github.sztuea.grpc.crawler.v1.GetCookieResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_crawler_proto_init() }
func file_protos_crawler_proto_init() {
	if File_protos_crawler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_crawler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCookieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_crawler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCookieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_crawler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_crawler_proto_goTypes,
		DependencyIndexes: file_protos_crawler_proto_depIdxs,
		MessageInfos:      file_protos_crawler_proto_msgTypes,
	}.Build()
	File_protos_crawler_proto = out.File
	file_protos_crawler_proto_rawDesc = nil
	file_protos_crawler_proto_goTypes = nil
	file_protos_crawler_proto_depIdxs = nil
}
